### ISSUE TITLE
bugs found by initial users

### ISSUE THREAD

**Issue by dgoffredo** [dgoffredo/stag#2]
Stag currently has the following bugs:

1. [X] Any types module that contains a `Choice` must `import typing`, because `typing.Union` is used in the signature of `__init__` for choice types.

2. [x] `gencodeutil.Choice` has a bug where it sets an attribute on itself, but also overloads `setattr`. Setting that attribute must be done using `object`'s version of the attribute setter, to avoid infinite recursion.

3. [x] Type annotations use strings for the names of user-generated types, so that the `class` definitions don't have to be topologically sorted (and we don't have to worry about cycles). The problem is, those annotations *remain* strings, so `from_jsonable`'s assumption that they are types (as in `class` objects) is wrong. To fix this, somehow `from_jsonable` needs access to the corresponding `class` object, which can be looked up in the generated types module, or perhaps added to a dedicated `dict`.

4. [x] It's inconvenient to require users to carry `gencodeutil.py` around with them. Instead, provide an option (perhaps the default) to inline the contents of `gencodeutil.py` with the generated code where necessary. Note that since `gencodeutil.py` contains code used by both the types and the utilities modules, this will not be trivial (might have to do away with the idea of having that code factored out at all). Alternatively, package `gencodeutil.py` properly for use by pip, dpkg, etc. The problem with this is now there are two moving pieces rather than one.

**Comment by dgoffredo** [comment]
I'm troubled by item 4. Not only does this mean duplicating almost 300 lines of python code in every generated messages module, but it also means adding a more complex subset of python to the code generator's internal AST representation.

Let's think of ways to bundle `gencodeutil.py` (or at least its contents) with the generated code without having it inline with the classes.

**Comment by drubin6** [comment]
You could just emit it as a separate module along with *msg[util].py. One benefit is that the utilization of gencodeutil will always be consistent with its implementation for each set of message modules.

**Comment by dgoffredo** [comment]
That's a good idea. 

It still leaves the problem of writing the contents of `gencodeutil` in the generator's AST language :(

Alternatively, I could patch together the common code without expressing it as an AST, but this would be a bad precedent.

However it ends up being done, I think this might be good output:

- `foomsg`: Defines classes from `foo.xsd`.
- `foomsgutil.py`: Defines foomsg-specific `to_jsonable`, `from_jsonable`, and name mappings.
- `_foomsg.py`: Contains the base classes `Sequence` and `Choice`, and whatever else `foomsg` might need.
- `_foomsgutil.py`: Defines the generic `to_jsonable`, `from_jsonable`, and the ISO-8601 crap.

Prefixing a "private" module with an underscore is something I've seen in the python standard library.

If four modules seems like too many, the underscored ones could be combined as they are now in `gencodeutil.py`, except that then I can't think of a good name for it. `foomsgimpl.py`? `_foomsg.py`? `foomsgdetail.py`? `_foomsgshared.py`? Strictly speaking, `foomsg.py` doesn't need to know about the ISO-8601 stuff and generic codecs, so four modules might be appropriate.

**Comment by dgoffredo** [comment]
All done.

**Comment by griffingarland** [comment]
Thanks!

**Comment by dgoffredo** [comment]
My pleasure.
